# Generated by Django 4.2 on 2023-04-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libray', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
