# Generated by Django 4.2 on 2023-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libray', '0002_remove_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('librarian', 'librarian')], max_length=10),
        ),
    ]
