# Generated by Django 4.2 on 2023-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libray", "0002_alter_assignedbook_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedbook",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
