# Generated by Django 4.2 on 2023-04-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libray', '0003_book_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=200),
        ),
    ]
