# Generated by Django 4.2 on 2023-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libray", "0003_assignedbook_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedbook",
            name="available_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
