# Generated by Django 4.2 on 2023-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libray', '0004_book_quantity_alter_book_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
