# Generated by Django 4.2 on 2023-05-15 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("libray", "0006_alter_assignedbook_date_returned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedbook",
            name="date_returned",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
