# Generated by Django 4.2 on 2023-04-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libray', '0007_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default=False, upload_to='libray_management/image'),
        ),
    ]
