# Generated by Django 4.2 on 2023-05-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libray", "0008_alter_assignedbook_date_returned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedbook",
            name="date_returned",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
