# Generated by Django 4.2 on 2023-04-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libray', '0013_alter_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='show_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
