# Generated by Django 4.2 on 2023-04-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libray', '0014_book_show_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='show_image',
        ),
    ]
