# Generated by Django 4.2 on 2023-05-01 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libray", "0017_assignbookhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="user",
        ),
        migrations.RemoveField(
            model_name="assignbookhistory",
            name="user",
        ),
        migrations.AddField(
            model_name="assignbookhistory",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
