# Generated by Django 4.2 on 2023-05-01 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libray", "0022_assignbookhistory_date_borrowed_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssignBookHistory",
            new_name="AssignBook",
        ),
    ]
