# Generated by Django 3.2.6 on 2023-05-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libray', '0023_rename_assignbookhistory_assignbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignbook',
            old_name='users_name',
            new_name='user',
        ),
    ]
