# Generated by Django 4.2 on 2023-05-02 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libray", "0024_rename_users_name_assignbook_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssignBook",
            new_name="AssignedBook",
        ),
    ]
